using System;
using System.Collections.Generic;
using System.Text;

namespace StoryFlags
{
    public static class StoryFlags
    {
        public static readonly List<string> AllFlags = [
            // Tutorials
            "played_Tutorial01",
            "played_Tutorial02",
            "tutorial_finished",
            "FirstTimeShop",
            "had_hub_interaction",
            "played_FirstHubReturn",
            "TutorialPopUp_Played_Ranking",
            "TutorialPopUp_Played_FragmentMap",
            "TutorialPopUp_Played_AntiSparks",
            "TutorialPopUp_Played_EnterShard",
            "TutorialPopUp_Played_CompletedFirstShard",
            "played_OpenItemRemoval",
            "has_met_animal_fashion",

            // Story conversations
            "played_01_StartGame01",
            "played_04_Main_SecondRun_Heir",
            "played_05_Main_AfterSecondRun",
            "played_06_Main_ThirdRun_Heir",
            "played_11_Main_FirstCaptain",
            "played_11_Main_SecondCaptain",
            "played_12_Main_Captain_HubArrival",
            "played_14_Main_AgencyEncountered",
            "played_15_Main_Shard01_Completed",
            "played_17_Main_MeetHeir",
            "played_18_Main_MeetHeirHub",
            "played_19_Main_HeirAgencyLeader",
            "played_20_Main_MeetAgencyLeader",
            "played_23_Main_Shard02_Completed_Sage",
            "played_25_Main_Wraith01",
            "played_26_Main_Wraith02",
            "played_27_Main_Wraith03",
            "played_28_Main_Wraith04",
            "played_29_Main_Wraith05",
            "played_30_Main_WraithHub",
            "played_31_Main_Apocalypse01",
            "played_32_Main_Apocalypse02",
            "played_33_Main_Apocalypse03",
            "played_34_Main_Apocalypse04",
            "played_35_Main_Apocalypse02",
            "played_35_Main_Timelines01",
            "played_36_Main_Timelines02",
            "played_37_Main_Timelines03",
            "played_38_Main_Timelines04",
            "played_39_Main_Timelines05",
            "played_40_Main_Timelines06",
            "played_41_Main_Timelines07",
            "played_42_Main_Timelines08",
            "played_43_Main_Timelines09",
            "played_44_Main_Timelines10",
            "played_45_Main_Timelines11",
            "played_46_Main_Timelines12",
            "played_47_Main_Timelines13",
            "played_48_Main_AgencyPurpose01",
            "played_49_Main_AgencyPurpose02",
            "played_50_Main_AgencyPurpose03",
            "played_51_Main_AgencyPurpose04",
            "played_52_Main_AgencyPurpose05",
            "played_53_Main_AgencyPurpose06",
            "played_54_Main_AgencyPurpose07",
            "played_55_Main_Resets01",
            "played_56_Main_Resets02",
            "played_57_Main_Resets03",
            "played_58_Main_Resets04",
            "played_59_Main_Resets05",
            "played_60_Main_AgencyLeader01",
            "played_61_Main_AgencyLeader02",
            "played_62_Main_AgencyLeader03",
            "played_63_Main_AgencyLeader04",
            "played_64_Main_AgencyLeader05",
            "played_65_Main_AgencyLeader06",
            "played_66_Main_ExistentialCrisis01",
            "played_67_Main_ExistentialCrisis02",
            "played_68_Main_ExistentialCrisis03",
            "played_69_Main_ExistentialCrisis04",
            "played_70_Main_ExistentialCrisis05",
            "played_71_Main_ExistentialCrisis06",
            "played_72_Main_ExistentialCrisis07",
            "played_73_Main_ExistentialCrisis08",
            "played_74_Main_ExistentialCrisis09",
            "played_75_Main_ExistentialCrisis10",
            "played_76_Main_Conviction01",
            "played_77_Main_Conviction02",
            "played_81_Main_FinalBoss_Start",
            "played_84_Main_EnteredSpark",
            "played_ResearcherHub01",
            "played_SageHeirConflict01"
        ];

    }
}
